server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
        routes:
          - id: STORE-SERVICE
            uri: lb://STORE-SERVICE
            predicates:
              - Path=/api/**